# From: https://developercommunity.visualstudio.com/content/problem/1151302/inconsistent-behavior-between-variablessecretvar-a.html

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
# Does not work without this:
variables:
  secretVar:  $[ variables['secretVar'] ]
  publicVar:  $[ variables['publicVar'] ]
  unsetVar:  $[ variables['unsetVar'] ]


steps:
- script: |      
    echo 'secretVar_Macro is:'         $secretVar_Macro
    echo 'secretVar_CompileTime is:'   $secretVar_CompileTime
    echo 'secretVar_Runtime is:'       $secretVar_Runtime
    echo 'secretVar_NoVariablesBlock_Macro is:'       $secretVar_NoVariablesBlock_Macro
    echo 'secretVar_NoVariablesBlock_CompileTime is:' $secretVar_NoVariablesBlock_CompileTime
    echo 'secretVar_NoVariablesBlock_Runtime is:'     $secretVar_NoVariablesBlock_Runtime

    echo
    echo 'publicVar_Macro is:'       $publicVar_Macro
    echo 'publicVar_CompileTime is:' $publicVar_CompileTime
    echo 'publicVar_Runtime is:'     $publicVar_Runtime
    echo 'publicVar_NoVariablesBlock_Macro is:'       $publicVar_NoVariablesBlock_Macro
    echo 'publicVar_NoVariablesBlock_CompileTime is:' $publicVar_NoVariablesBlock_CompileTime
    echo 'publicVar_NoVariablesBlock_Runtime is:'     $publicVar_NoVariablesBlock_Runtime

    echo
    echo 'unsetVar_Macro is:'       $unsetVar_Macro
    echo 'unsetVar_CompileTime is:' $unsetVar_CompileTime
    echo 'unsetVar_Runtime is:'     $unsetVar_Runtime
    echo 'unsetVar_NoVariablesBlock_Macro is:'       $unsetVar_NoVariablesBlock_Macro
    echo 'unsetVar_NoVariablesBlock_CompileTime is:' $unsetVar_NoVariablesBlock_CompileTime
    echo 'unsetVar_NoVariablesBlock_Runtime is:'     $unsetVar_NoVariablesBlock_Runtime


  env:
    secretVar_Macro: $(secretVar)
    secretVar_CompileTime: ${{variables.secretVar}}
    secretVar_Runtime: $[ variables['secretVar'] ]
    publicVar_Macro: $(publicVar)
    publicVar_CompileTime: ${{variables.publicVar}}
    publicVar_Runtime: $[ variables['publicVar'] ]
    unsetVar_Macro: $(unsetVar)
    unsetVar_CompileTime: ${{variables.unsetVar}}
    unsetVar_Runtime: $[ variables['unsetVar'] ]

- script: |
    echo
    echo 'info: No env: block is providfed for these echoes below here!'
    echo
    echo 'secretVar_Macro is:'         $secretVar_Macro
    echo 'secretVar_CompileTime is:'   $secretVar_CompileTime
    echo 'secretVar_Runtime is:'       $secretVar_Runtime
    echo 'secretVar_NoVariablesBlock_Macro is:'       $secretVar_NoVariablesBlock_Macro
    echo 'secretVar_NoVariablesBlock_CompileTime is:' $secretVar_NoVariablesBlock_CompileTime
    echo 'secretVar_NoVariablesBlock_Runtime is:'     $secretVar_NoVariablesBlock_Runtime

    echo
    echo 'publicVar_Macro is:'       $publicVar_Macro
    echo 'publicVar_CompileTime is:' $publicVar_CompileTime
    echo 'publicVar_Runtime is:'     $publicVar_Runtime
    echo 'publicVar_NoVariablesBlock_Macro is:'       $publicVar_NoVariablesBlock_Macro
    echo 'publicVar_NoVariablesBlock_CompileTime is:' $publicVar_NoVariablesBlock_CompileTime
    echo 'publicVar_NoVariablesBlock_Runtime is:'     $publicVar_NoVariablesBlock_Runtime

    echo
    echo 'unsetVar_Macro is:'       $unsetVar_Macro
    echo 'unsetVar_CompileTime is:' $unsetVar_CompileTime
    echo 'unsetVar_Runtime is:'     $unsetVar_Runtime
    echo 'unsetVar_NoVariablesBlock_Macro is:'       $unsetVar_NoVariablesBlock_Macro
    echo 'unsetVar_NoVariablesBlock_CompileTime is:' $unsetVar_NoVariablesBlock_CompileTime
    echo 'unsetVar_NoVariablesBlock_Runtime is:'     $unsetVar_NoVariablesBlock_Runtime

- script: |      
    echo 'secretVar_Macro is:'         $secretVar_Macro
    test "$secretVar_Macro" && echo "truthy" || echo "falsy"
    echo 'secretVar_CompileTime is:'   $secretVar_CompileTime
    test "$secretVar_CompileTime" && echo "truthy" || echo "falsy"
    echo 'secretVar_Runtime is:'       $secretVar_Runtime
    test "$secretVar_Runtime" && echo "truthy" || echo "falsy"
    echo 'secretVar_NoVariablesBlock_Macro is:'       $secretVar_NoVariablesBlock_Macro
    test "$secretVar_NoVariablesBlock_Macro" && echo "truthy" || echo "falsy"
    echo 'secretVar_NoVariablesBlock_CompileTime is:' $secretVar_NoVariablesBlock_CompileTime
    test "$secretVar_NoVariablesBlock_CompileTime" && echo "truthy" || echo "falsy"
    echo 'secretVar_NoVariablesBlock_Runtime is:'     $secretVar_NoVariablesBlock_Runtime
    test "$secretVar_NoVariablesBlock_Runtime" && echo "truthy" || echo "falsy"

    echo
    echo 'publicVar_Macro is:'         $publicVar_Macro
    test "$publicVar_Macro" && echo "truthy" || echo "falsy"
    echo 'publicVar_CompileTime is:'   $publicVar_CompileTime
    test "$publicVar_CompileTime" && echo "truthy" || echo "falsy"
    echo 'publicVar_Runtime is:'       $publicVar_Runtime
    test "$publicVar_Runtime" && echo "truthy" || echo "falsy"
    echo 'publicVar_NoVariablesBlock_Macro is:'       $publicVar_NoVariablesBlock_Macro
    test "$publicVar_NoVariablesBlock_Macro" && echo "truthy" || echo "falsy"
    echo 'publicVar_NoVariablesBlock_CompileTime is:' $publicVar_NoVariablesBlock_CompileTime
    test "$publicVar_NoVariablesBlock_CompileTime" && echo "truthy" || echo "falsy"
    echo 'publicVar_NoVariablesBlock_Runtime is:'     $publicVar_NoVariablesBlock_Runtime
    test "$publicVar_NoVariablesBlock_Runtime" && echo "truthy" || echo "falsy"

    echo
    echo 'unsetVar_Macro is:'         $unsetVar_Macro
    test "$unsetVar_Macro" && echo "truthy" || echo "falsy"
    echo 'unsetVar_CompileTime is:'   $unsetVar_CompileTime
    test "$unsetVar_CompileTime" && echo "truthy" || echo "falsy"
    echo 'unsetVar_Runtime is:'       $unsetVar_Runtime
    test "$unsetVar_Runtime" && echo "truthy" || echo "falsy"
    echo 'unsetVar_NoVariablesBlock_Macro is:'       $unsetVar_NoVariablesBlock_Macro
    test "$unsetVar_NoVariablesBlock_Macro" && echo "truthy" || echo "falsy"
    echo 'unsetVar_NoVariablesBlock_CompileTime is:' $unsetVar_NoVariablesBlock_CompileTime
    test "$unsetVar_NoVariablesBlock_CompileTime" && echo "truthy" || echo "falsy"
    echo 'unsetVar_NoVariablesBlock_Runtime is:'     $unsetVar_NoVariablesBlock_Runtime
    test "$unsetVar_NoVariablesBlock_Runtime" && echo "truthy" || echo "falsy"

  env:
    secretVar_Macro: $(secretVar)
    secretVar_CompileTime: ${{variables.secretVar}}
    secretVar_Runtime: $[ variables['secretVar'] ]
    publicVar_Macro: $(publicVar)
    publicVar_CompileTime: ${{variables.publicVar}}
    publicVar_Runtime: $[ variables['publicVar'] ]
    unsetVar_Macro: $(unsetVar)
    unsetVar_CompileTime: ${{variables.unsetVar}}
    unsetVar_Runtime: $[ variables['unsetVar'] ]