# From: https://developercommunity.visualstudio.com/content/problem/1151302/inconsistent-behavior-between-variablessecretvar-a.html

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
# Does not work without this:
variables:
  secretVar:  $[ variables['secretVar'] ]
  unsecretVar:  $[ variables['unsecretVar'] ]
  unsetVar:  $[ variables['unsetVar'] ]


steps:
- script: |      
    echo 'secretVar_Macro is:'         $secretVar_Macro
    echo 'secretVar_CompileTime is:'   $secretVar_CompileTime
    echo 'secretVar_Runtime is:'       $secretVar_Runtime
    echo 'secretVar_NoVariablesBlock_Macro is:'       $secretVar_NoVariablesBlock_Macro
    echo 'secretVar_NoVariablesBlock_CompileTime is:' $secretVar_NoVariablesBlock_CompileTime
    echo 'secretVar_NoVariablesBlock_Runtime is:'     $secretVar_NoVariablesBlock_Runtime

    echo 'unsecretVar_Macro is:'       $unsecretVar_Macro
    echo 'unsecretVar_CompileTime is:' $unsecretVar_CompileTime
    echo 'unsecretVar_Runtime is:'     $unsecretVar_Runtime
    echo 'unsecretVar_NoVariablesBlock_Macro is:'       $unsecretVar_NoVariablesBlock_Macro
    echo 'unsecretVar_NoVariablesBlock_CompileTime is:' $unsecretVar_NoVariablesBlock_CompileTime
    echo 'unsecretVar_NoVariablesBlock_Runtime is:'     $unsecretVar_NoVariablesBlock_Runtime

    echo 'unsetVar_Macro is:'       $unsetVar_Macro
    echo 'unsetVar_CompileTime is:' $unsetVar_CompileTime
    echo 'unsetVar_Runtime is:'     $unsetVar_Runtime
    echo 'unsetVar_NoVariablesBlock_Macro is:'       $unsetVar_NoVariablesBlock_Macro
    echo 'unsetVar_NoVariablesBlock_CompileTime is:' $unsetVar_NoVariablesBlock_CompileTime
    echo 'unsetVar_NoVariablesBlock_Runtime is:'     $unsetVar_NoVariablesBlock_Runtime


  env:
    secretVar_Macro: $(secretVar)
    secretVar_CompileTime: ${{variables.secretVar}}
    secretVar_Runtime: $[ variables['secretVar'] ]
    unsecretVar_Macro: $(unsecretVar)
    unsecretVar_CompileTime: ${{variables.unsecretVar}}
    unsecretVar_Runtime: $[ variables['unsecretVar'] ]
    unsetVar_Macro: $(unsetVar)
    unsetVar_CompileTime: ${{variables.unsetVar}}
    unsetVar_Runtime: $[ variables['unsetVar'] ]

- script: |
    echo
    echo 'info: No env: block is providfed for these echoes below here!'
    echo
    echo 'secretVar_Macro is:'         $secretVar_Macro
    echo 'secretVar_CompileTime is:'   $secretVar_CompileTime
    echo 'secretVar_Runtime is:'       $secretVar_Runtime
    echo 'secretVar_NoVariablesBlock_Macro is:'       $secretVar_NoVariablesBlock_Macro
    echo 'secretVar_NoVariablesBlock_CompileTime is:' $secretVar_NoVariablesBlock_CompileTime
    echo 'secretVar_NoVariablesBlock_Runtime is:'     $secretVar_NoVariablesBlock_Runtime

    echo 'unsecretVar_Macro is:'       $unsecretVar_Macro
    echo 'unsecretVar_CompileTime is:' $unsecretVar_CompileTime
    echo 'unsecretVar_Runtime is:'     $unsecretVar_Runtime
    echo 'unsecretVar_NoVariablesBlock_Macro is:'       $unsecretVar_NoVariablesBlock_Macro
    echo 'unsecretVar_NoVariablesBlock_CompileTime is:' $unsecretVar_NoVariablesBlock_CompileTime
    echo 'unsecretVar_NoVariablesBlock_Runtime is:'     $unsecretVar_NoVariablesBlock_Runtime

    echo 'unsetVar_Macro is:'       $unsetVar_Macro
    echo 'unsetVar_CompileTime is:' $unsetVar_CompileTime
    echo 'unsetVar_Runtime is:'     $unsetVar_Runtime
    echo 'unsetVar_NoVariablesBlock_Macro is:'       $unsetVar_NoVariablesBlock_Macro
    echo 'unsetVar_NoVariablesBlock_CompileTime is:' $unsetVar_NoVariablesBlock_CompileTime
    echo 'unsetVar_NoVariablesBlock_Runtime is:'     $unsetVar_NoVariablesBlock_Runtime
