# From: https://developercommunity.visualstudio.com/content/problem/1151302/inconsistent-behavior-between-variablessecretvar-a.html

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
# Does not work without this:
variables:
  secretVar:  $[ variables['secretVar'] ]
  publicVar2:  $[ variables['publicVar2'] ]
  unsetVar:  $[ variables['unsetVar'] ]


steps:
- script: |      
    echo 'secretVar_Macro is:'         "$secretVar_Macro"
    echo 'secretVar_CompileTime is:'   "$secretVar_CompileTime"
    echo 'secretVar_Runtime is:'       "$secretVar_RunTime"
    echo 'secretVar_NoVariablesBlock_Macro is:'       "$secretVar_NoVariablesBlock_Macro"
    echo 'secretVar_NoVariablesBlock_CompileTime is:' "$secretVar_NoVariablesBlock_CompileTime"
    echo 'secretVar_NoVariablesBlock_Runtime is:'     "$secretVar_NoVariablesBlock_RunTime"

    echo
    echo 'publicVar2_Macro is:'       "$publicVar2_Macro"
    echo 'publicVar2_CompileTime is:' "$publicVar2_CompileTime"
    echo 'publicVar2_Runtime is:'     "$publicVar2_RunTime"
    echo 'publicVar2_NoVariablesBlock_Macro is:'       "$publicVar2_NoVariablesBlock_Macro"
    echo 'publicVar2_NoVariablesBlock_CompileTime is:' "$publicVar2_NoVariablesBlock_CompileTime"
    echo 'publicVar2_NoVariablesBlock_Runtime is:'     "$publicVar2_NoVariablesBlock_RunTime"

    echo
    echo 'unsetVar_Macro is:'       "$unsetVar_Macro"
    echo 'unsetVar_CompileTime is:' "$unsetVar_CompileTime"
    echo 'unsetVar_Runtime is:'     "$unsetVar_RunTime"
    echo 'unsetVar_NoVariablesBlock_Macro is:'       "$unsetVar_NoVariablesBlock_Macro"
    echo 'unsetVar_NoVariablesBlock_CompileTime is:' "$unsetVar_NoVariablesBlock_CompileTime"
    echo 'unsetVar_NoVariablesBlock_Runtime is:'     "$unsetVar_NoVariablesBlock_RunTime"


  env:
    secretVar_Macro: $(secretVar)
    secretVar_CompileTime: ${{variables.secretVar}}
    secretVar_Runtime: $[ variables['secretVar'] ]
    secretVar_NoVariablesBlock_Macro: $(secretVar_NoVariablesBlock)
    secretVar_NoVariablesBlock_CompileTime: ${{variables.secretVar_NoVariablesBlock}}
    secretVar_NoVariablesBlock_Runtime: $[ variables['secretVar_NoVariablesBlock'] ]
    publicVar2_Macro: $(publicVar2)
    publicVar2_CompileTime: ${{variables.publicVar2}}
    publicVar2_Runtime: $[ variables['publicVar2'] ]
    publicVar2_NoVariablesBlock_Macro: $(publicVar2_NoVariablesBlock)
    publicVar2_NoVariablesBlock_CompileTime: ${{variables.publicVar2_NoVariablesBlock}}
    publicVar2_NoVariablesBlock_Runtime: $[ variables['publicVar2_NoVariablesBlock'] ]
    unsetVar_Macro: $(unsetVar)
    unsetVar_CompileTime: ${{variables.unsetVar}}
    unsetVar_Runtime: $[ variables['unsetVar'] ]
    unsetVar_NoVariablesBlock_Macro: $(unsetVar_NoVariablesBlock)
    unsetVar_NoVariablesBlock_CompileTime: ${{variables.unsetVar_NoVariablesBlock}}
    unsetVar_NoVariablesBlock_Runtime: $[ variables['unsetVar_NoVariablesBlock'] ]

- script: |
    echo
    echo 'info: No env: block is providfed for these echoes below here!'
    echo
    echo 'secretVar_Macro is:'         "$secretVar_Macro"
    echo 'secretVar_CompileTime is:'   "$secretVar_CompileTime"
    echo 'secretVar_Runtime is:'       "$secretVar_RunTime"
    echo 'secretVar_NoVariablesBlock_Macro is:'       "$secretVar_NoVariablesBlock_Macro"
    echo 'secretVar_NoVariablesBlock_CompileTime is:' "$secretVar_NoVariablesBlock_CompileTime"
    echo 'secretVar_NoVariablesBlock_Runtime is:'     "$secretVar_NoVariablesBlock_RunTime"

    echo
    echo 'publicVar2_Macro is:'       "$publicVar2_Macro"
    echo 'publicVar2_CompileTime is:' "$publicVar2_CompileTime"
    echo 'publicVar2_Runtime is:'     "$publicVar2_RunTime"
    echo 'publicVar2_NoVariablesBlock_Macro is:'       "$publicVar2_NoVariablesBlock_Macro"
    echo 'publicVar2_NoVariablesBlock_CompileTime is:' "$publicVar2_NoVariablesBlock_CompileTime"
    echo 'publicVar2_NoVariablesBlock_Runtime is:'     "$publicVar2_NoVariablesBlock_RunTime"

    echo
    echo 'unsetVar_Macro" is:'       "$unsetVar_Macro"
    echo 'unsetVar_CompileTime is:' "$unsetVar_CompileTime"
    echo 'unsetVar_Runtime is:'     "$unsetVar_RunTime"
    echo 'unsetVar_NoVariablesBlock_Macro is:'       "$unsetVar_NoVariablesBlock_Macro"
    echo 'unsetVar_NoVariablesBlock_CompileTime is:' "$unsetVar_NoVariablesBlock_CompileTime"
    echo 'unsetVar_NoVariablesBlock_Runtime is:'     "$unsetVar_NoVariablesBlock_RunTime"

- script: |      
    echo 'secretVar_Macro is:'         "$secretVar_Macro"
    test "${secretVar_Macro}" && echo "truthy" || echo "falsy"
    echo 'secretVar_CompileTime is:'   "$secretVar_CompileTime"
    test "${secretVar_CompileTime}" && echo "truthy" || echo "falsy"
    echo 'secretVar_Runtime is:'       "$secretVar_RunTime"
    test "${secretVar_Runtime}" && echo "truthy" || echo "falsy"
    echo 'secretVar_NoVariablesBlock_Macro is:'       "$secretVar_NoVariablesBlock_Macro"
    test "${secretVar_NoVariablesBlock_Macro}" && echo "truthy" || echo "falsy"
    echo 'secretVar_NoVariablesBlock_CompileTime is:' "$secretVar_NoVariablesBlock_CompileTime"
    test "${secretVar_NoVariablesBlock_CompileTime}" && echo "truthy" || echo "falsy"
    echo 'secretVar_NoVariablesBlock_Runtime is:'     "$secretVar_NoVariablesBlock_RunTime"
    test "${secretVar_NoVariablesBlock_Runtime}" && echo "truthy" || echo "falsy"

    echo
    echo 'publicVar2_Macro is:'         "$publicVar2_Macro"
    test "${publicVar2_Macro}" && echo "truthy" || echo "falsy"
    echo 'publicVar2_CompileTime is:'   "$publicVar2_CompileTime"
    test "${publicVar2_CompileTime}" && echo "truthy" || echo "falsy"
    echo 'publicVar2_Runtime is:'       "$publicVar2_RunTime"
    test "${publicVar2_Runtime}" && echo "truthy" || echo "falsy"
    echo 'publicVar2_NoVariablesBlock_Macro is:'       "$publicVar2_NoVariablesBlock_Macro"
    test "${publicVar2_NoVariablesBlock_Macro}" && echo "truthy" || echo "falsy"
    echo 'publicVar2_NoVariablesBlock_CompileTime is:' "$publicVar2_NoVariablesBlock_CompileTime"
    test "${publicVar2_NoVariablesBlock_CompileTime}" && echo "truthy" || echo "falsy"
    echo 'publicVar2_NoVariablesBlock_Runtime is:'     "$publicVar2_NoVariablesBlock_RunTime"
    test "${publicVar2_NoVariablesBlock_Runtime}" && echo "truthy" || echo "falsy"

    echo
    echo 'unsetVar_Macro is:'         "$unsetVar_Macro"
    test "${unsetVar_Macro}" && echo "truthy" || echo "falsy"
    echo 'unsetVar_CompileTime is:'   "$unsetVar_CompileTime"
    test "${unsetVar_CompileTime}" && echo "truthy" || echo "falsy"
    echo 'unsetVar_Runtime is:'       "$unsetVar_RunTime"
    test "${unsetVar_Runtime}" && echo "truthy" || echo "falsy"
    echo 'unsetVar_NoVariablesBlock_Macro is:'       "$unsetVar_NoVariablesBlock_Macro"
    test "${unsetVar_NoVariablesBlock_Macro}" && echo "truthy" || echo "falsy"
    echo 'unsetVar_NoVariablesBlock_CompileTime is:' "$unsetVar_NoVariablesBlock_CompileTime"
    test "${unsetVar_NoVariablesBlock_CompileTime}" && echo "truthy" || echo "falsy"
    echo 'unsetVar_NoVariablesBlock_Runtime is:'     "$unsetVar_NoVariablesBlock_RunTime"
    test "${unsetVar_NoVariablesBlock_Runtime}" && echo "truthy" || echo "falsy"

  env:
    secretVar_Macro: $(secretVar)
    secretVar_CompileTime: ${{variables.secretVar}}
    secretVar_Runtime: $[ variables['secretVar'] ]
    secretVar_NoVariablesBlock_Macro: $(secretVar_NoVariablesBlock)
    secretVar_NoVariablesBlock_CompileTime: ${{variables.secretVar_NoVariablesBlock}}
    secretVar_NoVariablesBlock_Runtime: $[ variables['secretVar_NoVariablesBlock'] ]
    publicVar2_Macro: $(publicVar2)
    publicVar2_CompileTime: ${{variables.publicVar2}}
    publicVar2_Runtime: $[ variables['publicVar2'] ]
    publicVar2_NoVariablesBlock_Macro: $(publicVar2_NoVariablesBlock)
    publicVar2_NoVariablesBlock_CompileTime: ${{variables.publicVar2_NoVariablesBlock}}
    publicVar2_NoVariablesBlock_Runtime: $[ variables['publicVar2_NoVariablesBlock'] ]
    unsetVar_Macro: $(unsetVar)
    unsetVar_CompileTime: ${{variables.unsetVar}}
    unsetVar_Runtime: $[ variables['unsetVar'] ]
    unsetVar_NoVariablesBlock_Macro: $(unsetVar_NoVariablesBlock)
    unsetVar_NoVariablesBlock_CompileTime: ${{variables.unsetVar_NoVariablesBlock}}
    unsetVar_NoVariablesBlock_Runtime: $[ variables['unsetVar_NoVariablesBlock'] ]