# From: https://developercommunity.visualstudio.com/content/problem/1151302/inconsistent-behavior-between-variablessecretvar-a.html

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
# Does not work without this:
# variables:
  # secrectVar:  $[ variables['secrectVar'] ]

steps:
- pwsh: |      
    echo secrectVar_Macro       $env:secrectVar_Macro
    echo secrectVar_CompileTime $env:secrectVar_CompileTime
    echo secrectVar_Runtime     $env:secrectVar_Runtime

  env:
    secrectVar_Macro: $(secrectVar)
    secrectVar_CompileTime: ${{variables.secrectVar}}
    secrectVar_Runtime: $[ variables['secrectVar'] ]