# From: https://developercommunity.visualstudio.com/content/problem/1151302/inconsistent-behavior-between-variablessecretvar-a.html

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
# Does not work without this:
# variables:
  # secretVar:  $[ variables['secretVar'] ]

steps:
- pwsh: |      
    echo secretVar_Macro       $env:secretVar_Macro
    echo secretVar_CompileTime $env:secretVar_CompileTime
    echo secretVar_Runtime     $env:secretVar_Runtime
    echo unsecretVar_Macro       $env:unsecretVar_Macro
    echo unsecretVar_CompileTime $env:unsecretVar_CompileTime
    echo unsecretVar_Runtime     $env:unsecretVar_Runtime

  env:
    secretVar_Macro: $(secretVar)
    secretVar_CompileTime: ${{variables.secretVar}}
    secretVar_Runtime: $[ variables['secretVar'] ]
    unsecretVar_Macro: $(unsecretVar)
    unsecretVar_CompileTime: ${{variables.unsecretVar}}
    unsecretVar_Runtime: $[ variables['unsecretVar'] ]