# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- pwsh: |
    if ( $True -eq $True ) {
      echo "true"
    } else {
      echo "false"
    }

- pwsh: |
    if ( $False -eq $False ) {
      echo "equal"
    } else {
      echo "not equal"
    }

- pwsh: |
    if ( $True -eq $False ) {
      echo "equal"
    } else {
      echo "not equal"
    }

- pwsh: |
    if ( $env:not_set -eq $False ) {
      echo "equal"
    } else {
      echo "not equal"
    }

- pwsh: |
    if ( $env:not_set -eq $True ) {
      echo "equal"
    } else {
      echo "not equal"
    }

- pwsh: |
    $env:set = $True
    if ( $env:set -eq $True ) {
      echo "equal"
    } else {
      echo "not equal"
    }

- pwsh: |
    $env:set = $True
    if ( $env:set -eq $False ) {
      echo "equal"
    } else {
      echo "not equal"
    }

- pwsh: |
    if ( False -eq $False ) {
      echo "equal"
    } else {
      echo "not equal"
    }

- pwsh: |
    if ( True -eq $True ) {
      echo "equal"
    } else {
      echo "not equal"
    }

- pwsh: |
    if ( $False -eq $False ) {
      echo "equal"
    } else {
      echo "not equal"
    }

- pwsh: |
    if ( False -eq $True ) {
      echo "equal"
    } else {
      echo "not equal"
    }