# From: https://developercommunity.visualstudio.com/content/problem/1151302/inconsistent-behavior-between-variablessecuredVar-a.html

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  securedVar:  ${{variables.securedVar}}
  publicVar:  ${{variables.publicVar}}
  unsetVar:  ${{variables.unsetVar}}

steps:
- script: |
    echo 'SECUREDVAR is:'               $SECUREDVAR
    echo 'SECUREDVAR_NOVARIABLESBLOCK is:'               $SECUREDVAR_NOVARIABLESBLOCK
    echo 'securedVar_Macro is:'         $securedVar_Macro
    echo 'securedVar_CompileTime is:'   $securedVar_CompileTime
    echo 'securedVar_Runtime is:'       $securedVar_Runtime
    echo 'securedVar_NoVariablesBlock_Macro is:'       $securedVar_NoVariablesBlock_Macro
    echo 'securedVar_NoVariablesBlock_CompileTime is:' $securedVar_NoVariablesBlock_CompileTime
    echo 'securedVar_NoVariablesBlock_Runtime is:'     $securedVar_NoVariablesBlock_Runtime

    echo
    echo 'PUBLICVAR is:'             $PUBLICVAR
    echo 'PUBLICVAR_NOVARIABLESBLOCK is:'             $PUBLICVARNOVARIABLESBLOCK
    echo 'publicVar_Macro is:'       $publicVar_Macro
    echo 'publicVar_CompileTime is:' $publicVar_CompileTime
    echo 'publicVar_Runtime is:'     $publicVar_Runtime
    echo 'publicVar_NoVariablesBlock_Macro is:'       $publicVar_NoVariablesBlock_Macro
    echo 'publicVar_NoVariablesBlock_CompileTime is:' $publicVar_NoVariablesBlock_CompileTime
    echo 'publicVar_NoVariablesBlock_Runtime is:'     $publicVar_NoVariablesBlock_Runtime

    echo
    echo 'UNSETVAR is:'             $UNSETVAR
    echo 'UNSETVAR_NOVARIABLES_BLOCK is:'             $UNSETVAR_NOVARIABLESBLOCK
    echo 'unsetVar_Macro is:'       $unsetVar_Macro
    echo 'unsetVar_CompileTime is:' $unsetVar_CompileTime
    echo 'unsetVar_Runtime is:'     $unsetVar_Runtime
    echo 'unsetVar_NoVariablesBlock_Macro is:'       $unsetVar_NoVariablesBlock_Macro
    echo 'unsetVar_NoVariablesBlock_CompileTime is:' $unsetVar_NoVariablesBlock_CompileTime
    echo 'unsetVar_NoVariablesBlock_Runtime is:'     $unsetVar_NoVariablesBlock_Runtime


  env:
    securedVar_Macro: $(securedVar)
    securedVar_CompileTime: ${{variables.securedVar}}
    securedVar_Runtime: $[variables.securedVar]
    securedVar_NoVariablesBlock_Macro: $(securedVar_NoVariablesBlock)
    securedVar_NoVariablesBlock_CompileTime: ${{variables.securedVar_NoVariablesBlock}}
    securedVar_NoVariablesBlock_Runtime: $[variables.securedVar_NoVariablesBlock]
    publicVar_Macro: $(publicVar)
    publicVar_CompileTime: ${{variables.publicVar}}
    publicVar_Runtime: $[variables.publicVar]
    publicVar_NoVariablesBlock_Macro: $(publicVar_NoVariablesBlock)
    publicVar_NoVariablesBlock_CompileTime: ${{variables.publicVar_NoVariablesBlock}}
    publicVar_NoVariablesBlock_Runtime: $[variables.publicVar_NoVariablesBlock]
    unsetVar_Macro: $(unsetVar)
    unsetVar_CompileTime: ${{variables.unsetVar}}
    unsetVar_Runtime: $[variables.unsetVar]
    unsetVar_NoVariablesBlock_Macro: $(unsetVar_NoVariablesBlock)
    unsetVar_NoVariablesBlock_CompileTime: ${{variables.unsetVar_NoVariablesBlock}}
    unsetVar_NoVariablesBlock_Runtime: $[variables.unsetVar_NoVariablesBlock]

- script: |
    echo
    echo 'info: No env: block is providfed for these echoes below here!'
    echo
    echo 'SECUREDVAR is:'               $SECUREDVAR
    echo 'SECUREDVAR_NOVARIABLESBLOCK is:'               $SECUREDVAR_NOVARIABLESBLOCK
    echo 'securedVar_Macro is:'         $securedVar_Macro
    echo 'securedVar_CompileTime is:'   $securedVar_CompileTime
    echo 'securedVar_Runtime is:'       $securedVar_Runtime
    echo 'securedVar_NoVariablesBlock_Macro is:'       $securedVar_NoVariablesBlock_Macro
    echo 'securedVar_NoVariablesBlock_CompileTime is:' $securedVar_NoVariablesBlock_CompileTime
    echo 'securedVar_NoVariablesBlock_Runtime is:'     $securedVar_NoVariablesBlock_Runtime

    echo
    echo 'PUBLICVAR is:'             $PUBLICVAR
    echo 'PUBLICVAR_NOVARIABLESBLOCK is:'             $PUBLICVARNOVARIABLESBLOCK
    echo 'publicVar_Macro is:'       $publicVar_Macro
    echo 'publicVar_CompileTime is:' $publicVar_CompileTime
    echo 'publicVar_Runtime is:'     $publicVar_Runtime
    echo 'publicVar_NoVariablesBlock_Macro is:'       $publicVar_NoVariablesBlock_Macro
    echo 'publicVar_NoVariablesBlock_CompileTime is:' $publicVar_NoVariablesBlock_CompileTime
    echo 'publicVar_NoVariablesBlock_Runtime is:'     $publicVar_NoVariablesBlock_Runtime

    echo
    echo 'UNSETVAR is:'             $UNSETVAR
    echo 'UNSETVAR_NOVARIABLES_BLOCK is:'             $UNSETVAR_NOVARIABLESBLOCK
    echo 'unsetVar_Macro is:'       $unsetVar_Macro
    echo 'unsetVar_CompileTime is:' $unsetVar_CompileTime
    echo 'unsetVar_Runtime is:'     $unsetVar_Runtime
    echo 'unsetVar_NoVariablesBlock_Macro is:'       $unsetVar_NoVariablesBlock_Macro
    echo 'unsetVar_NoVariablesBlock_CompileTime is:' $unsetVar_NoVariablesBlock_CompileTime
    echo 'unsetVar_NoVariablesBlock_Runtime is:'     $unsetVar_NoVariablesBlock_Runtime

- script: |
    echo 'SECUREDVAR is:'               $SECUREDVAR
    echo 'SECUREDVAR_NOVARIABLESBLOCK is:'               $SECUREDVAR_NOVARIABLESBLOCK
    echo 'securedVar_Macro is:'         $securedVar_Macro
    test "$securedVar_Macro" && echo "truthy" || echo "falsy"
    echo 'securedVar_CompileTime is:'   $securedVar_CompileTime
    test "$securedVar_CompileTime" && echo "truthy" || echo "falsy"
    echo 'securedVar_Runtime is:'       $securedVar_Runtime
    test "$securedVar_Runtime" && echo "truthy" || echo "falsy"
    echo 'securedVar_NoVariablesBlock_Macro is:'       $securedVar_NoVariablesBlock_Macro
    test "$securedVar_NoVariablesBlock_Macro" && echo "truthy" || echo "falsy"
    echo 'securedVar_NoVariablesBlock_CompileTime is:' $securedVar_NoVariablesBlock_CompileTime
    test "$securedVar_NoVariablesBlock_CompileTime" && echo "truthy" || echo "falsy"
    echo 'securedVar_NoVariablesBlock_Runtime is:'     $securedVar_NoVariablesBlock_Runtime
    test "$securedVar_NoVariablesBlock_Runtime" && echo "truthy" || echo "falsy"

    echo
    echo 'PUBLICVAR is:'             $PUBLICVAR
    echo 'PUBLICVAR_NOVARIABLESBLOCK is:'             $PUBLICVARNOVARIABLESBLOCK
    echo 'publicVar_Macro is:'         $publicVar_Macro
    test "$publicVar_Macro" && echo "truthy" || echo "falsy"
    echo 'publicVar_CompileTime is:'   $publicVar_CompileTime
    test "$publicVar_CompileTime" && echo "truthy" || echo "falsy"
    echo 'publicVar_Runtime is:'       $publicVar_Runtime
    test "$publicVar_Runtime" && echo "truthy" || echo "falsy"
    echo 'publicVar_NoVariablesBlock_Macro is:'       $publicVar_NoVariablesBlock_Macro
    test "$publicVar_NoVariablesBlock_Macro" && echo "truthy" || echo "falsy"
    echo 'publicVar_NoVariablesBlock_CompileTime is:' $publicVar_NoVariablesBlock_CompileTime
    test "$publicVar_NoVariablesBlock_CompileTime" && echo "truthy" || echo "falsy"
    echo 'publicVar_NoVariablesBlock_Runtime is:'     $publicVar_NoVariablesBlock_Runtime
    test "$publicVar_NoVariablesBlock_Runtime" && echo "truthy" || echo "falsy"

    echo
    echo 'UNSETVAR is:'             $UNSETVAR
    echo 'UNSETVAR_NOVARIABLES_BLOCK is:'             $UNSETVAR_NOVARIABLESBLOCK
    echo 'unsetVar_Macro is:'         $unsetVar_Macro
    test "$unsetVar_Macro" && echo "truthy" || echo "falsy"
    echo 'unsetVar_CompileTime is:'   $unsetVar_CompileTime
    test "$unsetVar_CompileTime" && echo "truthy" || echo "falsy"
    echo 'unsetVar_Runtime is:'       $unsetVar_Runtime
    test "$unsetVar_Runtime" && echo "truthy" || echo "falsy"
    echo 'unsetVar_NoVariablesBlock_Macro is:'       $unsetVar_NoVariablesBlock_Macro
    test "$unsetVar_NoVariablesBlock_Macro" && echo "truthy" || echo "falsy"
    echo 'unsetVar_NoVariablesBlock_CompileTime is:' $unsetVar_NoVariablesBlock_CompileTime
    test "$unsetVar_NoVariablesBlock_CompileTime" && echo "truthy" || echo "falsy"
    echo 'unsetVar_NoVariablesBlock_Runtime is:'     $unsetVar_NoVariablesBlock_Runtime
    test "$unsetVar_NoVariablesBlock_Runtime" && echo "truthy" || echo "falsy"

  env:
    securedVar_Macro: $(securedVar)
    securedVar_CompileTime: ${{variables.securedVar}}
    securedVar_Runtime: $[variables.securedVar]
    securedVar_NoVariablesBlock_Macro: $(securedVar_NoVariablesBlock)
    securedVar_NoVariablesBlock_CompileTime: ${{variables.securedVar_NoVariablesBlock}}
    securedVar_NoVariablesBlock_Runtime: $[variables.securedVar_NoVariablesBlock]
    publicVar_Macro: $(publicVar)
    publicVar_CompileTime: ${{variables.publicVar}}
    publicVar_Runtime: $[variables.publicVar]
    publicVar_NoVariablesBlock_Macro: $(publicVar_NoVariablesBlock)
    publicVar_NoVariablesBlock_CompileTime: ${{variables.publicVar_NoVariablesBlock}}
    publicVar_NoVariablesBlock_Runtime: $[variables.publicVar_NoVariablesBlock]
    unsetVar_Macro: $(unsetVar)
    unsetVar_CompileTime: ${{variables.unsetVar}}
    unsetVar_Runtime: $[variables.unsetVar]
    unsetVar_NoVariablesBlock_Macro: $(unsetVar_NoVariablesBlock)
    unsetVar_NoVariablesBlock_CompileTime: ${{variables.unsetVar_NoVariablesBlock}}
    unsetVar_NoVariablesBlock_Runtime: $[variables.unsetVar_NoVariablesBlock]
