jobs:
  - job: Windows_build_x86
    displayName: Windows Build x86
    variables:
      BUILD_ARCH: x86
      RunCoreMainTests: true

    pool:
      vmImage: vs2017-win2016

    steps:
      - template: templates/preparation.yml
        parameters:
          force32BitNode: true
