jobs:
  - job: Windows_build
    displayName: Windows Build

    strategy:
      maxParallel: 2
      matrix:
        x64:
          BUILD_ARCH: x64
          RunCoreMainTests: true
          NODE_VERSION: 10.0.0
        x86:
          BUILD_ARCH: x86
          RunCoreMainTests: true
          NODE_VERSION: 12.16.3

    pool:
      vmImage: vs2017-win2016

    steps:
      - template: templates/preparation.yml
        parameters:
          force32BitNode: ${{ ne(variables.BUILD_ARCH, 'x86') }}
